services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LOG4J_LOGGERS: "kafka=WARN,kafka.controller=WARN,kafka.log.LogCleaner=WARN,state.change.logger=WARN,kafka.network.RequestChannel=WARN,kafka.request.logger=WARN"
      KAFKA_LOG4J_ROOT_LOGLEVEL: "WARN"
    volumes:
      - kafkadata:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BOT_USERNAME: ${BOT_USERNAME}
      BOT_SECRET: ${BOT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  recommender:
    build: ../showrooms-recommender
    ports:
      - "8001:8001"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
    volumes:
      - ../showrooms-recommender/ml/model:/app/ml/model
    depends_on:
      postgres:
        condition: service_healthy

  bot:
    build: ../showrooms-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_SECRET: ${BOT_SECRET}
      DJANGO_API_URL: http://api:8000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
      api:
        condition: service_started

  frontend:
    build: ../showrooms-frontend
    ports:
      - "5173:80"
    depends_on:
      - api

  admin:
    build: ../showrooms-admin
    ports:
      - "5174:80"
    depends_on:
      - api

volumes:
  pgdata:
  kafkadata:
