# Generated by Django 4.2.27 on 2026-03-25 14:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomCar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_listings', to='cars.cartrim')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='dealerships.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='DealerCar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_offers', to='cars.cartrim')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_cars', to='dealerships.dealer')),
            ],
        ),
    ]
