# Generated by Django 4.2.27 on 2026-03-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_price'),
        ('dealerships', '0002_showroomcar_dealercar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealercar',
            name='available_quantity',
        ),
        migrations.AddField(
            model_name='showroomcar',
            name='source_dealer_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_to_showrooms', to='dealerships.dealercar'),
        ),
        migrations.AlterUniqueTogether(
            name='showroomcar',
            unique_together={('showroom', 'car_trim')},
        ),
    ]
