# Generated by Django 4.2.27 on 2026-03-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0003_remove_dealercar_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showroomcar',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='showroomcar',
            name='car_trim',
        ),
        migrations.RemoveField(
            model_name='showroomcar',
            name='showroom',
        ),
        migrations.RemoveField(
            model_name='showroomcar',
            name='source_dealer_car',
        ),
        migrations.DeleteModel(
            name='DealerCar',
        ),
        migrations.DeleteModel(
            name='ShowroomCar',
        ),
    ]
