# Generated by Django 4.2.27 on 2026-05-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authtoken_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='passport_number',
        ),
    ]
