# Generated by Django 4.2.27 on 2026-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
