# Generated by Django 4.2.27 on 2026-05-15 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0004_alter_showroomcar_unique_together_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDriveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_model_info', models.CharField(max_length=255)),
                ('color_name', models.CharField(blank=True, default='', max_length=50)),
                ('color_hex', models.CharField(blank=True, default='', max_length=7)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_requests', to='dealerships.showroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
