# Generated by Django 4.2.27 on 2026-05-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_testdriverequest_status_testdriverequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdriverequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
