# Generated by Django 4.2.27 on 2026-05-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_test_drive_request'),
        ('sales', '0004_preferred_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdriverequest',
            name='body_style',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='testdriverequest',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_drive_requests', to='cars.carmodel'),
        ),
        migrations.AddField(
            model_name='testdriverequest',
            name='drive_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='testdriverequest',
            name='engine_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testdriverequest',
            name='fuel_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='testdriverequest',
            name='transmission_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
