# Generated by Django 4.2.27 on 2026-05-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_testdriverequest_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdriverequest',
            name='day_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
