# Generated by Django 4.2.27 on 2026-03-13 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('engine_fuel_type', models.CharField(choices=[('GASOLINE', 'Бензин'), ('DIESEL', 'Дизель'), ('ELECTRIC', 'Электро')], max_length=30)),
                ('engine_hp', models.IntegerField(null=True)),
                ('engine_cylinders', models.IntegerField(null=True)),
                ('transmission_type', models.CharField(choices=[('AUTOMATIC', 'Автоматический'), ('MANUAL', 'Механический'), ('ROBOT', 'Робот'), ('DIRECT_DRIVE', 'Прямой привод (без коробки передач)')], max_length=30)),
                ('driven_wheels', models.CharField(choices=[('FWD', 'Передний привод'), ('RWD', 'Задний привод'), ('AWD', 'Постоянный полный привод'), ('4WD', 'Подключаемый полный привод')], max_length=30)),
                ('number_of_doors', models.PositiveIntegerField()),
                ('vehicle_style', models.CharField(choices=[('SEDAN', 'Седан'), ('SUV', 'Внедорожник'), ('COUPE', 'Купе'), ('CONVERTIBLE', 'Кабриолет'), ('HATCHBACK', 'Хэтчбек'), ('WAGON', 'Универсал'), ('PICKUP', 'Пикап'), ('MINIVAN', 'Минивэн'), ('VAN', 'Фургон')], max_length=30)),
                ('highway_mpg', models.IntegerField()),
                ('city_mpg', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='cars.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('SERVICE', 'Service')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealerships.dealer')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealerships.showroom')),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.cartrim')),
            ],
        ),
    ]
