# Generated by Django 4.2.27 on 2026-03-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
