# Generated by Django 4.2.27 on 2026-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_purchase_price_alter_car_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color_hex',
            field=models.CharField(blank=True, default='#cccccc', max_length=7),
        ),
        migrations.AddField(
            model_name='car',
            name='color_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartrim',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
