# Generated by Django 4.2.27 on 2026-05-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_cartrimimage_is_default_color_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cartrimimage',
            new_name='cars_cartri_trim_id_977b76_idx',
            old_name='cars_cartri_trim_id_isdef_idx',
        ),
        migrations.RenameIndex(
            model_name='cartrimimage',
            new_name='cars_cartri_trim_id_45d8d6_idx',
            old_name='cars_cartri_trim_id_color_idx',
        ),
    ]
