# Generated by Django 4.2.27 on 2026-04-10 11:00

import apps.telegram_bot.models
from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_client_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('token', models.CharField(default=secrets.token_hex, max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(default=apps.telegram_bot.models.get_expiry)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
        ),
    ]
